(ns clofin.settlement.statement-test
  "The simulated scheme's statement generator, and the ways it can be made
  wrong.

  Two properties matter here beyond the obvious ones. The generator is
  **deterministic** — the same request produces byte-identical output, including
  the statement reference, which is what makes re-ingesting one a replay rather
  than a second document. And it is **separate from the matcher**: this test
  asserts that separation from the source, because standing lesson **L-16** is
  the record of what agreement between a thing and itself is worth."
  (:require [clofin.money :as money]
            [clofin.recon.matching :as matching]
            [clofin.settlement.statement :as statement]
            [clojure.java.io :as io]
            [clojure.set :as set]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]])
  (:import [java.time Instant]))

(def ^:private from (Instant/parse "2026-08-01T00:00:00Z"))
(def ^:private to   (Instant/parse "2026-09-01T00:00:00Z"))

(def ^:private batch #uuid "11111111-1111-4111-8111-111111111111")
(def ^:private alpha #uuid "22222222-2222-4222-8222-222222222222")
(def ^:private beta  #uuid "33333333-3333-4333-8333-333333333333")

(def ^:private items
  [{:batch-id batch :instruction-id alpha :outcome "settled"
    :resolved-at (Instant/parse "2026-08-12T10:00:00Z") :amount (money/of "SGD" 125000)}
   {:batch-id batch :instruction-id beta :outcome "returned"
    :resolved-at (Instant/parse "2026-08-13T10:00:00Z") :amount (money/of "SGD" 90000)}])

(defn- generate
  [& {:keys [perturbation rows] :or {perturbation "none" rows items}}]
  (statement/generate {:scheme "SIM-RTGS" :currency "SGD"
                       :period-start from :period-end to
                       :perturbation perturbation :items rows}))

(defn- lines [doc] (get doc "lines"))
(defn- line-types [doc] (mapv #(get % "lineType") (lines doc)))
(defn- references [doc] (mapv #(get % "paymentReference") (lines doc)))
(defn- minor-units [doc] (mapv #(get-in % ["amount" "minorUnits"]) (lines doc)))

;; ---------------------------------------------------------------------------
;; L-16 — the generator and the matcher are different things
;; ---------------------------------------------------------------------------

(deftest the-generator-shares-no-matching-logic-with-the-matcher
  (testing "read from the source, because a runtime check would see a transitive
            require the file does not declare — the reason
            `clofin.ledger.purity-test` reads `ns` forms too"
    (let [form (with-open [r (java.io.PushbackReader.
                              (io/reader "src/clofin/settlement/statement.clj"))]
                 (read {:read-cond :allow} r))
          requires (->> form
                        (drop 2)
                        (filter #(and (seq? %) (= :require (first %))))
                        (mapcat rest)
                        (map #(str (if (sequential? %) (first %) %)))
                        set)]
      (is (contains? requires "clofin.recon.statement")
          "it must know the format it emits — that dependency is the direction")
      (is (not (contains? requires "clofin.recon.matching"))
          "a statement generated by the matcher's own rules proves the matcher
           agrees with itself, which is not a fact about anything (L-16)")
      (is (not (contains? requires "clofin.recon.repository"))
          "and it must not read the ledger: the two sides derive the amount, the
           date and the kind of movement by different routes")
      (is (not-any? #(str/starts-with? % "clofin.recon.") (disj requires "clofin.recon.statement"))
          (str "unexpected reconciliation dependencies: "
               (pr-str (remove #{"clofin.recon.statement"}
                               (filter #(str/starts-with? % "clofin.recon.") requires))))))))

;; ---------------------------------------------------------------------------
;; The unperturbed statement
;; ---------------------------------------------------------------------------

(deftest an-unperturbed-statement-reports-every-outcome-the-scheme-reached
  (let [doc (generate)]
    (is (= "SIM-CLOFIN-RECON-STATEMENT" (get doc "format")))
    (is (= 1 (get doc "formatVersion")))
    (is (true? (get doc "simulated"))
        "stated in the document itself: a statement saved to a file and read a
         year later must still say what it is")
    (is (= 2 (count (lines doc))))
    (is (= #{"settlement" "return"} (set (line-types doc))))
    (is (= #{(str alpha) (str beta)} (set (references doc))))
    (is (= [1 2] (mapv #(get % "lineNo") (lines doc))))))

(deftest a-timed-out-item-produces-no-line-at-all-and-that-is-the-product
  (testing "a statement line saying `timed out` would be the scheme reporting
            CloFin's own decision to stop waiting back to it. The money is still
            in 1300-IN-TRANSIT and correctly absent here — the pair ADR-0018's
            clearing account exists to make visible"
    (let [doc (generate :rows (conj items
                                    {:batch-id batch :instruction-id (random-uuid)
                                     :outcome "timed-out"
                                     :resolved-at (Instant/parse "2026-08-14T10:00:00Z")
                                     :amount (money/of "SGD" 5000)}))]
      (is (= 2 (count (lines doc))))))
  (testing "and neither does an item with no outcome yet"
    (let [doc (generate :rows [{:batch-id batch :instruction-id (random-uuid)
                                :outcome nil :resolved-at nil
                                :amount (money/of "SGD" 5000)}])]
      (is (empty? (lines doc))))))

(deftest the-period-is-half-open
  (testing "so consecutive statements chain exactly rather than double-counting
            whatever landed on the boundary"
    (let [at-start {:batch-id batch :instruction-id (random-uuid) :outcome "settled"
                    :resolved-at from :amount (money/of "SGD" 1)}
          at-end   {:batch-id batch :instruction-id (random-uuid) :outcome "settled"
                    :resolved-at to :amount (money/of "SGD" 2)}]
      (is (= 1 (count (lines (generate :rows [at-start])))) "start is included")
      (is (= 0 (count (lines (generate :rows [at-end])))) "end is excluded"))))

(deftest an-empty-period-is-a-real-statement
  (testing "it says the scheme did nothing, which is a fact rather than an error"
    (let [doc (generate :rows [])]
      (is (empty? (lines doc)))
      (is (str/starts-with? (get doc "statementReference") "SIM-STMT-")))))

;; ---------------------------------------------------------------------------
;; Determinism
;; ---------------------------------------------------------------------------

(deftest the-same-request-produces-the-same-document
  (testing "including the reference — which is what makes re-ingesting one a
            replay rather than a second document"
    (is (= (generate) (generate)))
    (is (= (generate :rows (reverse items)) (generate))
        "and the order the rows arrived in is not part of the answer")))

(deftest lines-are-ordered-by-their-own-reference-and-then-numbered
  (let [doc (generate)]
    (is (= (sort (mapv #(get % "schemeReference") (lines doc)))
           (mapv #(get % "schemeReference") (lines doc))))))

(deftest a-perturbed-statement-is-a-different-document-with-a-different-identity
  (testing "two different documents sharing one reference is the 409 case, not
            the replay case — so the class is part of the reference"
    (let [references (into #{} (map #(get (generate :perturbation %) "statementReference"))
                           (keys statement/perturbation-classes))]
      (is (= (count statement/perturbation-classes) (count references))))))

(deftest a-different-period-is-a-different-statement
  (is (not= (get (generate) "statementReference")
            (get (statement/generate {:scheme "SIM-RTGS" :currency "SGD"
                                      :period-start from
                                      :period-end (Instant/parse "2026-10-01T00:00:00Z")
                                      :perturbation "none" :items items})
                 "statementReference"))))

;; ---------------------------------------------------------------------------
;; Perturbations
;; ---------------------------------------------------------------------------

(deftest every-perturbation-class-does-what-its-name-says
  (let [clean (generate)]
    (testing "none"
      (is (= (lines clean) (lines (generate :perturbation "none")))))

    (testing "missing-line drops the first"
      (let [doc (generate :perturbation "missing-line")]
        (is (= 1 (count (lines doc))))
        (is (= (rest (references clean)) (references doc)))))

    (testing "amount-mismatch moves the first line's amount by a stated delta"
      (let [doc (generate :perturbation "amount-mismatch")]
        (is (= (+ (first (minor-units clean)) statement/amount-mismatch-minor)
               (first (minor-units doc))))
        (is (= (rest (minor-units clean)) (rest (minor-units doc)))
            "and nothing else")))

    (testing "unknown-line appends a payment CloFin never issued"
      (let [doc (generate :perturbation "unknown-line")]
        (is (= 3 (count (lines doc))))
        (is (= statement/unseen-payment-reference (last (references doc))))
        (is (not-any? #{statement/unseen-payment-reference} (references clean)))))

    (testing "duplicate-line repeats a line under a second line reference"
      (let [doc (generate :perturbation "duplicate-line")]
        (is (= 3 (count (lines doc))))
        (is (= (first (references clean)) (last (references doc)))
            "same payment claimed twice")
        (is (= 3 (count (distinct (map #(get % "schemeReference") (lines doc)))))
            "under distinct line references, which is what a real duplicate looks
             like")))

    (testing "shifted-value-date moves the first line's date and no other"
      (let [doc (generate :perturbation "shifted-value-date")]
        (is (not= (get (first (lines clean)) "valueDate")
                  (get (first (lines doc)) "valueDate")))
        (is (= (get (second (lines clean)) "valueDate")
               (get (second (lines doc)) "valueDate")))))

    (testing "flipped-line-type swaps settlement and return"
      (let [doc (generate :perturbation "flipped-line-type")]
        (is (not= (first (line-types clean)) (first (line-types doc))))
        (is (contains? #{"settlement" "return"} (first (line-types doc))))
        (is (= (rest (line-types clean)) (rest (line-types doc))))))

    (testing "reference-stripped removes the end-to-end reference and nothing else"
      (let [doc (generate :perturbation "reference-stripped")]
        (is (nil? (get (first (lines doc)) "paymentReference")))
        (is (= (get-in (first (lines clean)) ["amount" "minorUnits"])
               (get-in (first (lines doc)) ["amount" "minorUnits"])))
        (is (= (get (first (lines clean)) "valueDate")
               (get (first (lines doc)) "valueDate")))))))

(deftest perturbing-an-empty-statement-is-not-an-error
  (testing "an empty statement is a real statement, and refusing to perturb one
            would turn a legitimate request into an error at the least useful
            moment"
    (doseq [class (keys statement/perturbation-classes)]
      (is (some? (generate :perturbation class :rows [])) class))))

(deftest an-unknown-perturbation-class-is-refused-by-name
  (let [t (try (statement/assert-perturbation! "make-it-worse") nil (catch Exception e e))]
    (is (some? t))
    (is (= :validation (:clofin/error (ex-data t))))
    (is (= (vec (sort (keys statement/perturbation-classes))) (:known (ex-data t)))))
  (is (= "none" (statement/assert-perturbation! nil))
      "the statement the simulation would really send is the default, and it has
       a name rather than being the absence of a request"))

(deftest every-class-names-the-break-it-is-expected-to-produce
  (doseq [[class {:keys [expected-break summary]}] statement/perturbation-classes]
    (is (not (str/blank? summary)) (str class " must say what it does"))
    (when expected-break
      (is (contains? matching/break-kinds expected-break)
          (str class " expects a break kind the matcher cannot produce")))))

(deftest every-break-kind-is-reachable-from-some-named-class
  ;; Standing lesson **L-10**: a break kind reachable only from a unit test
  ;; constructing values by hand is a schema path with no product path behind
  ;; it. `expectation-unmatched` is reached by `missing-line`; the rest have a
  ;; class each.
  (let [expected (into #{} (keep :expected-break) (vals statement/perturbation-classes))]
    (is (empty? (set/difference (set matching/break-kinds) expected))
        (str "break kinds no perturbation class produces: "
             (pr-str (set/difference (set matching/break-kinds) expected))))))

;; ---------------------------------------------------------------------------
;; The line reference, and the SIM- discipline
;; ---------------------------------------------------------------------------

(deftest every-reference-the-generator-emits-is-sim-prefixed
  (let [doc (generate :perturbation "unknown-line")]
    (is (str/starts-with? (get doc "statementReference") "SIM-"))
    (doseq [line (lines doc)]
      (is (str/starts-with? (get line "schemeReference") "SIM-")))
    (is (str/starts-with? statement/unseen-payment-reference "SIM-"))))

(deftest a-line-reference-is-the-statements-own-and-not-a-response-reference
  (testing "a statement is a separate document with its own line references;
            reusing the settlement response's would make it look like a second
            copy of that table"
    (doseq [line (lines (generate))]
      (is (str/starts-with? (get line "schemeReference") statement/line-reference-prefix)))))

(deftest the-end-to-end-reference-is-the-instruction-id
  (testing "which is what makes a returned payment's original and its retry
            unambiguous: they are different instructions with different ids
            (ADR-0019)"
    (is (= #{(str alpha) (str beta)} (set (references (generate)))))))
