(ns clofin.recon.break-state
  "The reconciliation break lifecycle, held as data.

  `transitions` **is** the lifecycle — not a description of one. Every rule
  about which event may follow which state is in that map, and every function
  here reads it rather than restating it. This is the shape
  `clofin.payments.state` established and ADR-0014 records, copied deliberately
  rather than reinvented: a transition rule written as an `if` inside a service
  is the failure both namespaces exist to prevent, because the table stops being
  the truth and nobody finds out until an audit.

  Because the lifecycle is a value it is tested by **enumeration** rather than
  by sampling — `clofin.recon.break-state-test` walks every (state, event) pair,
  so a pair nobody thought to write a case for is still covered — and it is
  **drawn** from the same value: `docs/diagrams/reconciliation-break-lifecycle.md`
  is generated by `clofin.tools.diagrams` and checked in both directions
  (ADR-0020 RULE 1, ADR-0021).

  ## What a break is, and why the states are these three

  A break is a tracked, owned, ageing fact — `DOMAIN_MODEL.md` §1: *not* a
  discrepancy somebody will look at later. So:

  | State | Meaning |
  |---|---|
  | `open` | Discovered by matching and assigned, and nobody has picked it up |
  | `investigating` | An actor has taken it on and is working it |
  | `resolved` | Closed by a posted adjustment — terminal |

  **Assignment is the transition.** A break becomes investigated by somebody
  taking ownership of it, so `:assign` is one fact rather than two, and it emits
  one audit event. Re-assigning an already-investigated break leaves the state
  where it is and is therefore *not* an arrow: it is governed by
  `reassignable-states` below, the same way `clofin.payments.state/mutable-states`
  governs amending a draft.

  **`resolved` is reached only by a posted adjustment**, which is why the arrow
  is named `:resolve` and driven from
  `clofin.recon.service/post-adjustment!` and nowhere else. There is no
  \"written off\" state: nothing in this increment can drive one, and a state
  with no driver is a promise the product does not keep (standing lesson
  **L-10**).

  **Age is derived, never stored.** It is `now - opened-at`, computed by
  whoever reads the break — `clofin.recon.repository` does it in SQL, on the
  same connection as the read. A stored age is wrong the moment it is written,
  for the same reason a stored balance is (ADR-0008).

  Pure: no database, no clock, no identifier generation."
  (:require [clofin.error :as err]))

;; ---------------------------------------------------------------------------
;; The lifecycle
;; ---------------------------------------------------------------------------

(def transitions
  "State to `{event → next state}`. The diagram is generated from here, never
  the other way around.

  Every arrow has a driver, and that is a rule rather than a coincidence:
  `:assign` is driven by `POST /reconciliation-breaks/{id}/assignment` and
  `:resolve` by the transaction in which an adjustment posts. An arrow nothing
  drives is a schema path with no product path behind it (standing lesson
  **L-10**), and this table was written after the endpoints it describes
  precisely so that could not happen."
  {:open          {:assign :investigating, :resolve :resolved}
   :investigating {:resolve :resolved}
   :resolved      {}})

(def initial-state
  "Where a break begins. Matching opens breaks; a caller cannot create one at
  all, let alone in another state."
  :open)

(def states
  "Every state a break may hold. Sorted, so error detail and generated
  documentation are stable between runs. Identical to
  `recon_break_state_known` in migration `0012`."
  (into (sorted-set) (keys transitions)))

(def events
  "Every event the lifecycle recognises, across all states."
  (into (sorted-set) (mapcat keys) (vals transitions)))

(defn- outgoing
  "The events permitted from `state`, as `{event → next state}`.

  An unrecognised state is a defect rather than a caller error — the column
  carries a check constraint listing exactly these three — so it is reported as
  one rather than being quietly treated as terminal. Treating an unknown state
  as terminal would refuse every operation on the row and look, from outside,
  exactly like a correctly resolved break."
  [state]
  (or (get transitions state)
      (err/invalid! (str "Unknown reconciliation break state: " state)
                    {:state (str state) :known (mapv name states)})))

(defn known?
  "True when `state` is a state the lifecycle recognises."
  [state]
  (contains? transitions state))

(defn terminal?
  "True when no event leaves `state`.

  **Derived from the table rather than declared**, so a state that acquires an
  outgoing arrow stops being terminal in the same commit that gives it one —
  and the generated diagram stops drawing it as terminal in that commit too."
  [state]
  (empty? (outgoing state)))

(def terminal-states
  "The terminal set, derived. Never a second list: a hand-kept copy is the thing
  that goes stale while every test that reads it keeps passing."
  (into (sorted-set) (filter terminal?) states))

(defn permitted-events
  "The events `state` allows, sorted."
  [state]
  (into (sorted-set) (keys (outgoing state))))

(defn permitted?
  "True when `event` may be applied to `state`."
  [state event]
  (contains? (outgoing state) event))

(defn transition
  "The state reached by applying `event` to `state`.

  Throws a `:conflict` naming the attempted transition and what would have been
  permitted instead. A caller that has been refused needs to know which of its
  assumptions was wrong — `409` alone leaves it guessing between \"somebody
  already resolved this\" and \"this break was never yours\", which are very
  different situations for whoever is holding it."
  [state event]
  (or (get (outgoing state) event)
      (err/conflict!
       (str "Cannot " (name event) " a reconciliation break that is " (name state))
       {:break-state (name state)
        :attempted   (name event)
        :permitted   (mapv name (permitted-events state))})))

;; ---------------------------------------------------------------------------
;; A rule about state that is not a transition
;; ---------------------------------------------------------------------------

(def reassignable-states
  "States in which a break's assignee may be changed **without** moving it.

  `:investigating` only. Assigning an `open` break is the `:assign` transition —
  it is how a break becomes investigated — so it is an arrow rather than a
  member here; and a `resolved` break has an owner of record that must not be
  rewritten, because who resolved what is the history an investigation reads.

  This lives beside the table rather than inside a handler for the reason
  `clofin.payments.state/mutable-states` does: a rule about state written into a
  handler is a rule the next handler restates differently."
  #{:investigating})

(defn reassignable?
  "True when a break in `state` may be reassigned in place."
  [state]
  (outgoing state)                    ; an unrecognised state is a defect, not a `false`
  (contains? reassignable-states state))

(defn assert-assignable!
  "Throw a `:conflict` unless a break in `state` may take a new assignee at all.

  A break is assignable when assigning it is a transition (`:assign` is
  permitted) **or** when it is reassignable in place. Both halves are read from
  the values above rather than from a status test, so the one endpoint that sets
  an assignee cannot drift from the lifecycle it drives."
  [state]
  (when-not (or (permitted? state :assign) (reassignable? state))
    (err/conflict!
     (str "Cannot assign a reconciliation break that is " (name state))
     {:break-state    (name state)
      :attempted      "assign"
      :assignable-in  (mapv name (sort (into (into (sorted-set) reassignable-states)
                                             (filter #(permitted? % :assign))
                                             states)))}))
  state)
