(ns clofin.settlement.statement
  "The simulated scheme's own account statement, and the ways it can be wrong.

  > CloFin is not connected to any bank, payment scheme or central bank.
  > Nothing here reads a file drop or a socket: this namespace computes what the
  > **simulated** scheme would say about the payments it was given, from the
  > settlement records of what it did. The document it produces is in CloFin's
  > own format — `clofin.recon.statement/format-name` — which is deliberately
  > not camt.053, MT940, BAI2 or any real scheme's schema.

  ## Why the generator lives here and not in `clofin.recon`

  Standing lesson **L-16**: *agreement is only worth something between values
  produced by different things.* A statement generated by the matcher's own
  rules, from the matcher's own keys, proves that the matcher agrees with
  itself — which is not a fact about anything.

  So the two sides are separated on purpose and the separation is structural
  rather than a convention:

  | | The scheme's side (here) | CloFin's side (`clofin.recon`) |
  |---|---|---|
  | Reads | `settlement_batch_item`, `payment_instruction` | `journal_entry`, `journal_line` |
  | Dates a movement by | when the item resolved | when the entry occurred |
  | Says what kind of movement it was from | the item's outcome | the entry's counter-account |
  | Amount from | the instruction | the posted journal line |

  Nothing in this namespace requires anything under `clofin.recon`, and nothing
  under `clofin.recon` requires this. There is no shared match key and no shared
  matching function — a line is matched to a movement by
  `clofin.recon.matching`, which has never seen this file.

  ## Perturbations

  A generator that could only produce agreement would be a generator that could
  not test disagreement. `perturbation-classes` names each way a statement can
  be wrong; each is applied deterministically to the first line in the
  statement's canonical order (or, for the two that add a line, appended), so a
  reviewer can predict the break it produces before running anything.

  Pure: no database, no clock, no identifier generation. The period, the rows
  and the perturbation come from the caller."
  (:require [clofin.error :as err]
            [clofin.money :as money]
            [clofin.recon.statement :as statement]
            [clojure.string :as str])
  (:import [java.time Instant ZoneOffset]))

;; ---------------------------------------------------------------------------
;; From an item outcome to a statement line
;; ---------------------------------------------------------------------------

(def outcome-line-types
  "What the scheme calls each outcome it reported.

  `timed-out` is deliberately absent, and its absence is the most important
  thing in this namespace. A timed-out item is one the scheme **never answered
  about**; a statement line saying so would be the scheme reporting CloFin's own
  decision to stop waiting back to it. The money is still in
  `1300-IN-TRANSIT` on CloFin's books and it is correctly absent from the
  statement — which is exactly the case ADR-0018's clearing account exists to
  make visible, and the case that shows the model working rather than an edge
  case."
  {"settled"  "settlement"
   "returned" "return"})

(def line-reference-prefix
  "A statement line's own reference. `SIM-` prefixed like everything else a
  simulated scheme emits, and deliberately **not** the reference the scheme used
  on its response to the settlement batch: a statement is a separate document
  with its own line references, and reusing the response reference would make
  the statement look like a second copy of the response table."
  "SIM-STMT-LN")

(defn- value-date
  "The calendar date the scheme dates a movement to: the UTC day of the instant
  it resolved the item.

  UTC rather than a local zone so the answer does not depend on where the
  process runs. CloFin dates the same movement by the UTC day of its journal
  entry's `occurred_at` — a second instant, recorded by a different write — so
  the two agree except when a settlement transaction spans UTC midnight, and a
  `value-date-mismatch` break there is the correct answer rather than a defect.
  ADR-0023 states that consequence rather than leaving it to be discovered."
  [^Instant instant]
  (.toLocalDate (.atZone instant ZoneOffset/UTC)))

(defn- item->line
  [{:keys [batch-id instruction-id outcome resolved-at amount]}]
  {:scheme-reference  (str line-reference-prefix "-" batch-id "-" instruction-id)
   :payment-reference (str instruction-id)
   :line-type         (get outcome-line-types outcome)
   :amount            amount
   :value-date        (value-date resolved-at)})

(defn- reportable?
  "True when the scheme would report this item on a statement for the period.

  Resolved to an outcome the scheme actually reached — `settled` or `returned` —
  inside `[from, to)`, the same half-open period every other CloFin read uses
  (ADR-0011), so consecutive statements chain exactly rather than
  double-counting whatever landed on the boundary."
  [{:keys [outcome resolved-at]} ^Instant from ^Instant to]
  (and (contains? outcome-line-types outcome)
       (some? resolved-at)
       (not (.isBefore ^Instant resolved-at from))
       (.isBefore ^Instant resolved-at to)))

;; ---------------------------------------------------------------------------
;; Perturbations
;; ---------------------------------------------------------------------------

(def unseen-payment-reference
  "The end-to-end reference the `unknown-line` class puts on its extra line.

  A constant rather than a generated identifier: the same request must produce
  the same document, or ingesting a statement twice would not be a replay. It is
  a reference CloFin has never issued, which is the whole point — the line
  reports money the scheme says it moved and CloFin never saw settle."
  "SIM-UNSEEN-PAYMENT")

(def value-date-shift-days
  "How far `shifted-value-date` moves a line. Three days: far enough to be
  unambiguous, small enough to be the sort of drift a real statement shows."
  3)

(def amount-mismatch-minor
  "How much `amount-mismatch` adds to a line, in minor units of the statement's
  currency. Added rather than multiplied so the delta is the same whatever the
  amount, and so a test can state the expected difference."
  100)

(defn- flip-line-type
  [line-type]
  (first (disj (set (vals outcome-line-types)) line-type)))

(def perturbation-classes
  "Every way a generated statement can be made wrong, and the break each is
  expected to produce.

  Named classes rather than free parameters: a caller asks for *the missing-line
  case*, not for a set of edits, so a reviewer reading a UAT script or a test
  can predict the outcome. `none` is a class like any other and is the default —
  the statement that agrees completely is the one AC-1 turns on, and it deserves
  a name rather than being the absence of a request.

  Every break kind in `clofin.recon.matching/break-kinds` is reachable from one
  of these through the public ingestion path, which is standing lesson
  **L-10**'s requirement: a break kind reachable only from a unit test
  constructing values by hand is a schema path with no product path behind it."
  {"none"
   {:expected-break nil
    :summary "The statement the simulated scheme would really send. Everything matches."}

   "missing-line"
   {:expected-break "expectation-unmatched"
    :summary (str "The first line is dropped. CloFin's ledger records a movement "
                  "the statement does not report — the direction of the check that "
                  "a statement-line-only reconciliation would miss entirely.")}

   "amount-mismatch"
   {:expected-break "amount-mismatch"
    :summary (str "The first line's amount is increased by "
                  amount-mismatch-minor " minor units. The reference still "
                  "identifies the movement, so the two records are matched and "
                  "disagree — which is the disagreement worth finding.")}

   "unknown-line"
   {:expected-break "statement-line-unmatched"
    :summary (str "A line is appended carrying a payment reference CloFin has "
                  "never issued: money the scheme says it moved and CloFin never "
                  "saw settle.")}

   "duplicate-line"
   {:expected-break "duplicate-statement-line"
    :summary (str "The first line is repeated under a second line reference. One "
                  "copy matches the movement; the other is a second claim on a "
                  "movement already accounted for.")}

   "shifted-value-date"
   {:expected-break "value-date-mismatch"
    :summary (str "The first line's value date moves " value-date-shift-days
                  " days later. Reference and amount still identify the movement.")}

   "flipped-line-type"
   {:expected-break "line-type-mismatch"
    :summary (str "The first line reports a settlement as a return, or the other "
                  "way round. The scheme and CloFin agree that money moved and "
                  "disagree about where it went.")}

   "reference-stripped"
   {:expected-break nil
    :summary (str "The first line loses its end-to-end reference. It still matches "
                  "— by rule R4, on amount and value date alone — and the match "
                  "records that it was the weaker rule that found it.")}})

(defn assert-perturbation!
  "Return `class`, or throw naming the classes that exist."
  [class]
  (let [c (or class "none")]
    (when-not (contains? perturbation-classes c)
      (err/invalid! (str "Unknown perturbation class: " c)
                    {:perturbation (str c)
                     :known (vec (sort (keys perturbation-classes)))}))
    c))

(defn- perturb
  "Apply one perturbation class to a statement's lines.

  Every class edits or appends deterministically, and a class with no first line
  to edit leaves the statement alone rather than raising: an empty statement is
  a real statement — it says the scheme did nothing this period — and refusing
  to perturb one would turn a legitimate request into an error at the least
  useful moment."
  [class currency ^Instant from lines]
  (let [head (first lines)
        edit (fn [f] (into [(f head)] (rest lines)))]
    (case class
      "none"          lines
      "missing-line"  (vec (rest lines))
      "amount-mismatch"
      (if head
        (edit #(update % :amount
                       (fn [a] (money/of (:currency a)
                                         (+ (:minor-units a) amount-mismatch-minor)))))
        lines)
      "shifted-value-date"
      (if head (edit #(update % :value-date (fn [d] (.plusDays d value-date-shift-days)))) lines)
      "flipped-line-type"
      (if head (edit #(update % :line-type flip-line-type)) lines)
      "reference-stripped"
      (if head (edit #(assoc % :payment-reference nil)) lines)
      "duplicate-line"
      (if head
        (conj (vec lines) (assoc head :scheme-reference
                                 (str (:scheme-reference head) "-DUPLICATE")))
        lines)
      "unknown-line"
      (conj (vec lines)
            {:scheme-reference  (str line-reference-prefix "-" unseen-payment-reference)
             :payment-reference unseen-payment-reference
             :line-type         "settlement"
             :amount            (if head
                                  (:amount head)
                                  (money/of currency 100000))
             :value-date        (value-date from)}))))

;; ---------------------------------------------------------------------------
;; The statement
;; ---------------------------------------------------------------------------

(defn- compact-instant
  "An instant rendered for use inside a reference: seconds precision, no
  punctuation a reader has to escape."
  [^Instant instant]
  (str/replace (str (.truncatedTo instant java.time.temporal.ChronoUnit/SECONDS)) #"[-:]" ""))

(defn statement-reference
  "The identity of a generated statement, derived from what it is a statement
  *of*.

  Deterministic, so asking for the same statement twice produces the same
  reference and the second ingestion is recognised as a replay rather than
  admitted as a second document. The perturbation class is part of it because a
  perturbed statement is a different document, and two different documents
  sharing one reference is the `409` case rather than the replay case."
  [{:keys [scheme currency period-start period-end perturbation]}]
  (str "SIM-STMT-" scheme "-" currency
       "-" (compact-instant period-start)
       "-" (compact-instant period-end)
       "-" (str/upper-case (str/replace perturbation "-" ""))))

(defn generate
  "The statement the simulated scheme would send for a period, as a document.

      (generate {:scheme \"SIM-RTGS\" :currency \"SGD\"
                 :period-start inst :period-end inst
                 :perturbation \"none\"
                 :items [{:batch-id … :instruction-id … :outcome …
                          :resolved-at … :amount …} …]})

  `items` are the settlement memberships the caller read for the period —
  `clofin.settlement.repository/resolved-items-for` produces them. Which of
  them the scheme would report, in what order, and with what on each line is
  decided here.

  Lines are ordered by their scheme reference and then numbered, so the same
  inputs produce byte-identical output whatever order the rows arrived in. The
  returned value is a **wire document**: string keys, ready to be handed to a
  caller or posted straight back to `POST /reconciliation-statements`."
  [{:keys [scheme currency period-start period-end perturbation items]}]
  (let [class (assert-perturbation! perturbation)
        lines (->> items
                   (filter #(reportable? % period-start period-end))
                   (map item->line)
                   (sort-by :scheme-reference)
                   vec
                   (perturb class currency period-start))]
    {"format"             statement/format-name
     "formatVersion"      statement/format-version
     ;; Stated in the document itself, not only in the API description: a
     ;; statement saved to a file and read a year later must still say what it
     ;; is. Every other CloFin document that describes simulated activity
     ;; carries the same flag.
     "simulated"          true
     "scheme"             scheme
     "currency"           currency
     "statementReference" (statement-reference {:scheme scheme :currency currency
                                                :period-start period-start
                                                :period-end period-end
                                                :perturbation class})
     "periodStart"        (str period-start)
     "periodEnd"          (str period-end)
     "perturbation"       class
     "lines"
     (into []
           (map-indexed
            (fn [i line]
              (cond-> {"lineNo"          (inc i)
                       "schemeReference" (:scheme-reference line)
                       "lineType"        (:line-type line)
                       "amount"          (money/->wire (:amount line))
                       "valueDate"       (str (:value-date line))}
                (:payment-reference line)
                (assoc "paymentReference" (:payment-reference line)))))
           lines)}))
